import path from 'node:path'

import { resolveSvgDesign } from '../design-resolve.js';
import type { Box } from '../geometry.js';
import type {
  StructureDraft,
  StructureDraftNode,
} from './types.js'
import { formatPx } from './utils.js'

const renderNodeHtml = ({
  designHtmlDir,
  node,
  nodeById,
  parentBox,
}: {
  designHtmlDir: string
  node: StructureDraftNode
  nodeById: Map<string, StructureDraftNode>
  parentBox: Box
}) => {
  const left = node.box.x - parentBox.x
  const top = node.box.y - parentBox.y
  const style = [
    'position:absolute',
    `left:${formatPx(left)}`,
    `top:${formatPx(top)}`,
    `width:${formatPx(node.box.width)}`,
    `height:${formatPx(node.box.height)}`,
  ].join(';')

  const attrs = [
    `id="${node.id}"`,
    `data-draft-role="${node.role}"`,
    `style="${style}"`,
  ].join(' ')

  const children: string[] = []

  node.children.forEach((childId) => {
    const childNode = nodeById.get(childId)
    if (!childNode) return
    children.push(
      renderNodeHtml({
        designHtmlDir,
        node: childNode,
        nodeById,
        parentBox: node.box,
      }),
    )
  })

  return `<${node.tag} ${attrs}>${children.join('')}</${node.tag}>`
}

const createHtmlScaffoldFromDraft = ({
  artifactPaths,
  design,
  structureDraft,
}: {
  artifactPaths: {
    scaffoldDecisionsPath: string
    structureDraftPath: string
  }
  design: Awaited<ReturnType<typeof resolveSvgDesign>>
  structureDraft: StructureDraft
}) => {
  const nodeById = new Map(
    structureDraft.nodes.map((node) => [node.id, node] as const),
  )
  const renderEntryDir = path.dirname(design.svgPath)
  const rootBox: Box = {
    height: design.height,
    width: design.width,
    x: 0,
    y: 0,
  }

  const content = structureDraft.topLevelNodeIds
    .map((nodeId) => nodeById.get(nodeId))
    .filter((node): node is StructureDraftNode => Boolean(node))
    .map((node) =>
      renderNodeHtml({
        designHtmlDir: renderEntryDir,
        node,
        nodeById,
        parentBox: rootBox,
      }),
    )
    .join('\n      ')

  const toRepoRelative = (value: string) =>
    path.relative(process.cwd(), value).replaceAll(path.sep, '/')

  return `<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${design.designName}</title>
    <style>
      * {
        box-sizing: border-box;
      }

      body {
        margin: 0;
        background: transparent;
        font-family: "Noto Sans CJK SC", "Source Han Sans SC", "Microsoft YaHei", sans-serif;
      }

      .design-page {
        position: relative;
        width: ${formatPx(design.width)};
        height: ${formatPx(design.height)};
        overflow: hidden;
        background: transparent;
      }

      [data-draft-role="container"],
      [data-draft-role="group"],
      [data-draft-role="repeat-list"],
      [data-draft-role="repeat-item"],
      [data-draft-role="token-row"],
      [data-draft-role="token-cell"] {
        position: absolute;
      }
    </style>
  </head>
  <body>
    <main class="design-page">
      <!-- Semi-auto scaffold generated by generate-design.ts -->
      <!-- SVG geometry builds the initial structure and shell placement. -->
      <!-- Artifacts: ${toRepoRelative(artifactPaths.structureDraftPath)}, ${toRepoRelative(
        artifactPaths.scaffoldDecisionsPath,
      )} -->
      ${content}
    </main>
  </body>
</html>
`
}

export { createHtmlScaffoldFromDraft }
